version: '3.8'
services:
   web:
       build: .
       command: bash -c "python src/preprocess.py data/raw_data/example data_example.csv && python src/train.py -m BNB && coverage run src/predict.py -m BNB  && coverage report -m"
       ports:
           - 77:70
       image: altairzero/mle-template:latest